//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TabletApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TabletApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smartPIMS.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ascanwaveform {
            get {
                object obj = ResourceManager.GetObject("ascanwaveform", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset.
        /// </summary>
        internal static string AssetTitle {
            get {
                return ResourceManager.GetString("AssetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.xml.
        /// </summary>
        internal static string AutoFillCompanyFilename {
            get {
                return ResourceManager.GetString("AutoFillCompanyFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe.xml.
        /// </summary>
        internal static string AutoFillProbeFilename {
            get {
                return ResourceManager.GetString("AutoFillProbeFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop auto-read?.
        /// </summary>
        internal static string AutoReadCancelCaption {
            get {
                return ResourceManager.GetString("AutoReadCancelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you&apos;d like to stop the current auto-read session?.
        /// </summary>
        internal static string AutoReadCancelMessage {
            get {
                return ResourceManager.GetString("AutoReadCancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading....
        /// </summary>
        internal static string AutoReadUploadProgress {
            get {
                return ResourceManager.GetString("AutoReadUploadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blue_button_big {
            get {
                object obj = ResourceManager.GetObject("blue_button_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blue_button_down {
            get {
                object obj = ResourceManager.GetObject("blue_button_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blue_button_left {
            get {
                object obj = ResourceManager.GetObject("blue_button_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blue_button_right {
            get {
                object obj = ResourceManager.GetObject("blue_button_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blue_button_small {
            get {
                object obj = ResourceManager.GetObject("blue_button_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blue_button_up {
            get {
                object obj = ResourceManager.GetObject("blue_button_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel commissioning?.
        /// </summary>
        internal static string BuildNetworkCancelCaption {
            get {
                return ResourceManager.GetString("BuildNetworkCancelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the commissioning process now?.
        /// </summary>
        internal static string BuildNetworkCancelMessage {
            get {
                return ResourceManager.GetString("BuildNetworkCancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string ButtonBack {
            get {
                return ResourceManager.GetString("ButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string ButtonCamera {
            get {
                return ResourceManager.GetString("ButtonCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud.
        /// </summary>
        internal static string ButtonCloud {
            get {
                return ResourceManager.GetString("ButtonCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string ButtonCopy {
            get {
                return ResourceManager.GetString("ButtonCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Logging.
        /// </summary>
        internal static string ButtonDisableLogging {
            get {
                return ResourceManager.GetString("ButtonDisableLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string ButtonDone {
            get {
                return ResourceManager.GetString("ButtonDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Globals.
        /// </summary>
        internal static string ButtonEditGlobals {
            get {
                return ResourceManager.GetString("ButtonEditGlobals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string ButtonEmail {
            get {
                return ResourceManager.GetString("ButtonEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Logging.
        /// </summary>
        internal static string ButtonEnableLogging {
            get {
                return ResourceManager.GetString("ButtonEnableLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        internal static string ButtonKeyboard {
            get {
                return ResourceManager.GetString("ButtonKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Config.
        /// </summary>
        internal static string ButtonLoadConfig {
            get {
                return ResourceManager.GetString("ButtonLoadConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string ButtonNext {
            get {
                return ResourceManager.GetString("ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string ButtonNo {
            get {
                return ResourceManager.GetString("ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string ButtonPrevious {
            get {
                return ResourceManager.GetString("ButtonPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read All.
        /// </summary>
        internal static string ButtonReadAll {
            get {
                return ResourceManager.GetString("ButtonReadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Selected.
        /// </summary>
        internal static string ButtonReadSelected {
            get {
                return ResourceManager.GetString("ButtonReadSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string ButtonReplace {
            get {
                return ResourceManager.GetString("ButtonReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-scan.
        /// </summary>
        internal static string ButtonRescan {
            get {
                return ResourceManager.GetString("ButtonRescan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string ButtonReset {
            get {
                return ResourceManager.GetString("ButtonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Address.
        /// </summary>
        internal static string ButtonResetAddress {
            get {
                return ResourceManager.GetString("ButtonResetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        internal static string ButtonReview {
            get {
                return ResourceManager.GetString("ButtonReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scratch.
        /// </summary>
        internal static string ButtonScratch {
            get {
                return ResourceManager.GetString("ButtonScratch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string ButtonSend {
            get {
                return ResourceManager.GetString("ButtonSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string ButtonStart {
            get {
                return ResourceManager.GetString("ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string ButtonUpload {
            get {
                return ResourceManager.GetString("ButtonUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View AScan.
        /// </summary>
        internal static string ButtonViewAscan {
            get {
                return ResourceManager.GetString("ButtonViewAscan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Summary.
        /// </summary>
        internal static string ButtonViewSummary {
            get {
                return ResourceManager.GetString("ButtonViewSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Thickness.
        /// </summary>
        internal static string ButtonViewThickness {
            get {
                return ResourceManager.GetString("ButtonViewThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string ButtonYes {
            get {
                return ResourceManager.GetString("ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap camera_icon {
            get {
                object obj = ResourceManager.GetObject("camera_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel current operation?.
        /// </summary>
        internal static string CancelCaption {
            get {
                return ResourceManager.GetString("CancelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel commissioning?.
        /// </summary>
        internal static string CancelDsiCaption {
            get {
                return ResourceManager.GetString("CancelDsiCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the commissioning?  All data will be lost and the DSI will be reset to factory default settings..
        /// </summary>
        internal static string CancelDsiDataMessage {
            get {
                return ResourceManager.GetString("CancelDsiDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the current operation?.
        /// </summary>
        internal static string CancelMessage {
            get {
                return ResourceManager.GetString("CancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking admin privileges....
        /// </summary>
        internal static string CheckAdminProgressString {
            get {
                return ResourceManager.GetString("CheckAdminProgressString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking that logging is enabled....
        /// </summary>
        internal static string CheckingDataLoggerEnabled {
            get {
                return ResourceManager.GetString("CheckingDataLoggerEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cloud_icon {
            get {
                object obj = ResourceManager.GetObject("cloud_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Point ID.
        /// </summary>
        internal static string CollectionPointIDTitle {
            get {
                return ResourceManager.GetString("CollectionPointIDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Point.
        /// </summary>
        internal static string CollectionPointTitle {
            get {
                return ResourceManager.GetString("CollectionPointTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap commissioning {
            get {
                object obj = ResourceManager.GetObject("commissioning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to go into commissiong mode?  This mode will modify the DSIs on the network..
        /// </summary>
        internal static string CommissioningConfirmMessage {
            get {
                return ResourceManager.GetString("CommissioningConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string CompanyTitle {
            get {
                return ResourceManager.GetString("CompanyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for DSI....
        /// </summary>
        internal static string ConnectDsiProgress {
            get {
                return ResourceManager.GetString("ConnectDsiProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String connected?.
        /// </summary>
        internal static string ConnectStringCaption {
            get {
                return ResourceManager.GetString("ConnectStringCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure the string is fully connected.  Proceed?.
        /// </summary>
        internal static string ConnectStringMessage {
            get {
                return ResourceManager.GetString("ConnectStringMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to all probes?.
        /// </summary>
        internal static string CopyProbesCaption {
            get {
                return ResourceManager.GetString("CopyProbesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to overwrite all probes with the current data?.
        /// </summary>
        internal static string CopyProbesMessage {
            get {
                return ResourceManager.GetString("CopyProbesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying to probes....
        /// </summary>
        internal static string CopyToProbesProgress {
            get {
                return ResourceManager.GetString("CopyToProbesProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Reading Number.
        /// </summary>
        internal static string DataLoggerCurrentShotNumber {
            get {
                return ResourceManager.GetString("DataLoggerCurrentShotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Readings.
        /// </summary>
        internal static string DataLoggerTotalShots {
            get {
                return ResourceManager.GetString("DataLoggerTotalShots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default (English).
        /// </summary>
        internal static string DefaultLanguage {
            get {
                return ResourceManager.GetString("DefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.smartpims.com.
        /// </summary>
        internal static string DefaultWebUrl {
            get {
                return ResourceManager.GetString("DefaultWebUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_file {
            get {
                object obj = ResourceManager.GetObject("delete_file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescriptionTitle {
            get {
                return ResourceManager.GetString("DescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .contents.
        /// </summary>
        internal static string DirMappingFilename {
            get {
                return ResourceManager.GetString("DirMappingFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .meta.
        /// </summary>
        internal static string DirMetaFilename {
            get {
                return ResourceManager.GetString("DirMetaFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dsi {
            get {
                object obj = ResourceManager.GetObject("dsi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dsi_active {
            get {
                object obj = ResourceManager.GetObject("dsi_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dsi_blank {
            get {
                object obj = ResourceManager.GetObject("dsi_blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dsi_error {
            get {
                object obj = ResourceManager.GetObject("dsi_error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dsi_error_active {
            get {
                object obj = ResourceManager.GetObject("dsi_error_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dsi_warning {
            get {
                object obj = ResourceManager.GetObject("dsi_warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dsi_warning_active {
            get {
                object obj = ResourceManager.GetObject("dsi_warning_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of DSIs.
        /// </summary>
        internal static string DsiCountTitle {
            get {
                return ResourceManager.GetString("DsiCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DSI could not be reset..
        /// </summary>
        internal static string DsiResetFail {
            get {
                return ResourceManager.GetString("DsiResetFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DSI has been successfully reset..
        /// </summary>
        internal static string DsiResetSuccess {
            get {
                return ResourceManager.GetString("DsiResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSI Temperature.
        /// </summary>
        internal static string DsiTempTitle {
            get {
                return ResourceManager.GetString("DsiTempTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap email_icon {
            get {
                object obj = ResourceManager.GetObject("email_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EmailDefaultMessage {
            get {
                return ResourceManager.GetString("EmailDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EmailDefaultSubject {
            get {
                return ResourceManager.GetString("EmailDefaultSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email could not be sent.
        /// </summary>
        internal static string EmailProgressFail {
            get {
                return ResourceManager.GetString("EmailProgressFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending email....
        /// </summary>
        internal static string EmailProgressSending {
            get {
                return ResourceManager.GetString("EmailProgressSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email was successfully sent.
        /// </summary>
        internal static string EmailProgressSuccess {
            get {
                return ResourceManager.GetString("EmailProgressSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A camera could not be found..
        /// </summary>
        internal static string ErrorCameraNotFound {
            get {
                return ResourceManager.GetString("ErrorCameraNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smartPIMS Error.
        /// </summary>
        internal static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is a required field..
        /// </summary>
        internal static string ErrorCommAddrRequired {
            get {
                return ResourceManager.GetString("ErrorCommAddrRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is a required field..
        /// </summary>
        internal static string ErrorCommCityRequired {
            get {
                return ResourceManager.GetString("ErrorCommCityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection point location is required..
        /// </summary>
        internal static string ErrorCommCollectionPointLocationRequired {
            get {
                return ResourceManager.GetString("ErrorCommCollectionPointLocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection point name is required..
        /// </summary>
        internal static string ErrorCommCollectionPointNameRequired {
            get {
                return ResourceManager.GetString("ErrorCommCollectionPointNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company ID is a required field..
        /// </summary>
        internal static string ErrorCommCompanyIdRequired {
            get {
                return ResourceManager.GetString("ErrorCommCompanyIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name is a required field..
        /// </summary>
        internal static string ErrorCommCompanyNameRequired {
            get {
                return ResourceManager.GetString("ErrorCommCompanyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company is a required field..
        /// </summary>
        internal static string ErrorCommCompanyRequired {
            get {
                return ResourceManager.GetString("ErrorCommCompanyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A DSI could not be found.  Would you like to scan again?.
        /// </summary>
        internal static string ErrorCommDsiNotFound {
            get {
                return ResourceManager.GetString("ErrorCommDsiNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have administrator rights on this device in order to commission a DSI..
        /// </summary>
        internal static string ErrorCommissioningUserNotAdmin {
            get {
                return ResourceManager.GetString("ErrorCommissioningUserNotAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of DSIs is 32..
        /// </summary>
        internal static string ErrorCommNumDsis {
            get {
                return ResourceManager.GetString("ErrorCommNumDsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of DSIs is a required field..
        /// </summary>
        internal static string ErrorCommNumDsisRequired {
            get {
                return ResourceManager.GetString("ErrorCommNumDsisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reading the DSI and probe data..
        /// </summary>
        internal static string ErrorCommReadDsiAndProbes {
            get {
                return ResourceManager.GetString("ErrorCommReadDsiAndProbes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The probe could not be read..
        /// </summary>
        internal static string ErrorCommReadProbeFailed {
            get {
                return ResourceManager.GetString("ErrorCommReadProbeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error was encountered while setting the DSI address..
        /// </summary>
        internal static string ErrorCommSetAddress {
            get {
                return ResourceManager.GetString("ErrorCommSetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DSI could not be read using the new address {0}..
        /// </summary>
        internal static string ErrorCommSetAddressRead {
            get {
                return ResourceManager.GetString("ErrorCommSetAddressRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of site, plant or asset is required..
        /// </summary>
        internal static string ErrorCommSitePlantAssetRequired {
            get {
                return ResourceManager.GetString("ErrorCommSitePlantAssetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State is a required field..
        /// </summary>
        internal static string ErrorCommStateRequired {
            get {
                return ResourceManager.GetString("ErrorCommStateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while writing the DSI info..
        /// </summary>
        internal static string ErrorCommWriteDsiInfoException {
            get {
                return ResourceManager.GetString("ErrorCommWriteDsiInfoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information failed to write to the DSI.  Please check the logs..
        /// </summary>
        internal static string ErrorCommWriteDsiInfoFailed {
            get {
                return ResourceManager.GetString("ErrorCommWriteDsiInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while writing the probe data..
        /// </summary>
        internal static string ErrorCommWriteProbeDataException {
            get {
                return ResourceManager.GetString("ErrorCommWriteProbeDataException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The probe data failed to be written.  Please check the logs..
        /// </summary>
        internal static string ErrorCommWriteProbeDataFailed {
            get {
                return ResourceManager.GetString("ErrorCommWriteProbeDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code is a required field..
        /// </summary>
        internal static string ErrorCommZipRequired {
            get {
                return ResourceManager.GetString("ErrorCommZipRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The From field is a required field..
        /// </summary>
        internal static string ErrorEmailFromMissing {
            get {
                return ResourceManager.GetString("ErrorEmailFromMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The To field is a required field..
        /// </summary>
        internal static string ErrorEmailToMissing {
            get {
                return ResourceManager.GetString("ErrorEmailToMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This DSI has an unknown model designator.  The 1st generation Modbus model will be assumed for this DSI..
        /// </summary>
        internal static string ErrorInvalidDsiModel {
            get {
                return ResourceManager.GetString("ErrorInvalidDsiModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters..
        /// </summary>
        internal static string ErrorInvalidNewPassword {
            get {
                return ResourceManager.GetString("ErrorInvalidNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.  Please try again..
        /// </summary>
        internal static string ErrorInvalidPassword {
            get {
                return ResourceManager.GetString("ErrorInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The found DSI is a data logger DSI that contains previously logged data.  This data must be read before entering commissioning.  Continue to “Read All”?.
        /// </summary>
        internal static string ErrorLoggerHasShotsMessage {
            get {
                return ResourceManager.GetString("ErrorLoggerHasShotsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSI Contains Logged Data.
        /// </summary>
        internal static string ErrorLoggerHasShotsTitle {
            get {
                return ResourceManager.GetString("ErrorLoggerHasShotsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reading of a logger DSI cannot be interrupted..
        /// </summary>
        internal static string ErrorLoggerReadInterrupt {
            get {
                return ResourceManager.GetString("ErrorLoggerReadInterrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout occurred while logging in..
        /// </summary>
        internal static string ErrorLoginTimeout {
            get {
                return ResourceManager.GetString("ErrorLoginTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout occurred while logging out..
        /// </summary>
        internal static string ErrorLogoutTimeout {
            get {
                return ResourceManager.GetString("ErrorLogoutTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max files exceeded.  Only the first {0} will be taken..
        /// </summary>
        internal static string ErrorMaxReviewFilenames {
            get {
                return ResourceManager.GetString("ErrorMaxReviewFilenames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No DSIs could be found on the network..
        /// </summary>
        internal static string ErrorNoDsisFound {
            get {
                return ResourceManager.GetString("ErrorNoDsisFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email settings have not been set.  Please go to Settings and enter your settings..
        /// </summary>
        internal static string ErrorNoEmailSettings {
            get {
                return ResourceManager.GetString("ErrorNoEmailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get your current location..
        /// </summary>
        internal static string ErrorNoLocation {
            get {
                return ResourceManager.GetString("ErrorNoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only uncommissioned DSIs were found on the network.  Please commission the DSIs first..
        /// </summary>
        internal static string ErrorOnlyFactoryDsiFound {
            get {
                return ResourceManager.GetString("ErrorOnlyFactoryDsiFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.  Please try again..
        /// </summary>
        internal static string ErrorPasswordMatch {
            get {
                return ResourceManager.GetString("ErrorPasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while performing the thickness measurements..
        /// </summary>
        internal static string ErrorReadProbes {
            get {
                return ResourceManager.GetString("ErrorReadProbes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout occurred while performing the thickness measurements..
        /// </summary>
        internal static string ErrorReadProbesTimeout {
            get {
                return ResourceManager.GetString("ErrorReadProbesTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current probe model is unrecognized, therefore the probe cannot be reset to its defaults..
        /// </summary>
        internal static string ErrorResetProbe {
            get {
                return ResourceManager.GetString("ErrorResetProbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while saving..
        /// </summary>
        internal static string ErrorSave {
            get {
                return ResourceManager.GetString("ErrorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving the measurement CSV files..
        /// </summary>
        internal static string ErrorSaveMeasurementCsv {
            get {
                return ResourceManager.GetString("ErrorSaveMeasurementCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving the summary file..
        /// </summary>
        internal static string ErrorSaveSummary {
            get {
                return ResourceManager.GetString("ErrorSaveSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving the DSI XML..
        /// </summary>
        internal static string ErrorSaveXml {
            get {
                return ResourceManager.GetString("ErrorSaveXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scanned number of DSIs does not match the number of populated DSIs..
        /// </summary>
        internal static string ErrorScannedCounts {
            get {
                return ResourceManager.GetString("ErrorScannedCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scanned number of DSIs does not match the returned number of DSIs..
        /// </summary>
        internal static string ErrorScannedCounts2 {
            get {
                return ResourceManager.GetString("ErrorScannedCounts2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while scanning the DSI network..
        /// </summary>
        internal static string ErrorScanNetwork {
            get {
                return ResourceManager.GetString("ErrorScanNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout occurred while scanning the DSI network..
        /// </summary>
        internal static string ErrorScanNetworkTimeout {
            get {
                return ResourceManager.GetString("ErrorScanNetworkTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while sending the email message..
        /// </summary>
        internal static string ErrorSendEmail {
            get {
                return ResourceManager.GetString("ErrorSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout occurred while sending the email message..
        /// </summary>
        internal static string ErrorSendEmailTimeout {
            get {
                return ResourceManager.GetString("ErrorSendEmailTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception has occured.  Please restart the application..
        /// </summary>
        internal static string ErrorUnhandledException {
            get {
                return ResourceManager.GetString("ErrorUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while uploading..
        /// </summary>
        internal static string ErrorUpload {
            get {
                return ResourceManager.GetString("ErrorUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout occurred while uploading..
        /// </summary>
        internal static string ErrorUploadTimeout {
            get {
                return ResourceManager.GetString("ErrorUploadTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Gate settings.  Please adjust all active Gates to start and end within the viewable Ascan range..
        /// </summary>
        internal static string ErrorVelocityParams {
            get {
                return ResourceManager.GetString("ErrorVelocityParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing global info.  Please check the logs..
        /// </summary>
        internal static string ErrorWriteGlobalInfo {
            get {
                return ResourceManager.GetString("ErrorWriteGlobalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smartPIMS.
        /// </summary>
        internal static string GeneralMessageCaption {
            get {
                return ResourceManager.GetString("GeneralMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting current location....
        /// </summary>
        internal static string GetLocationProgress {
            get {
                return ResourceManager.GetString("GetLocationProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gray_button {
            get {
                object obj = ResourceManager.GetObject("gray_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hamburger_on {
            get {
                object obj = ResourceManager.GetObject("hamburger_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap header_bg {
            get {
                object obj = ResourceManager.GetObject("header_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home {
            get {
                object obj = ResourceManager.GetObject("home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hookup {
            get {
                object obj = ResourceManager.GetObject("hookup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing network....
        /// </summary>
        internal static string InitializeNetworkProgress {
            get {
                return ResourceManager.GetString("InitializeNetworkProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keyboard {
            get {
                object obj = ResourceManager.GetObject("keyboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log.txt.
        /// </summary>
        internal static string LogFilename {
            get {
                return ResourceManager.GetString("LogFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable data logger?.
        /// </summary>
        internal static string LoggerEnableCaption {
            get {
                return ResourceManager.GetString("LoggerEnableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to turn the data logger on?.
        /// </summary>
        internal static string LoggerEnableQuestion {
            get {
                return ResourceManager.GetString("LoggerEnableQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Logger Off.
        /// </summary>
        internal static string LoggerOffString {
            get {
                return ResourceManager.GetString("LoggerOffString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Logger On.
        /// </summary>
        internal static string LoggerOnString {
            get {
                return ResourceManager.GetString("LoggerOnString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Temperature.
        /// </summary>
        internal static string MaterialTempTitle {
            get {
                return ResourceManager.GetString("MaterialTempTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        internal static string MaximumTitle {
            get {
                return ResourceManager.GetString("MaximumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean.
        /// </summary>
        internal static string MeanTitle {
            get {
                return ResourceManager.GetString("MeanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alltmls.csv.
        /// </summary>
        internal static string MeasurementDsiFileName {
            get {
                return ResourceManager.GetString("MeasurementDsiFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tml{0}.csv.
        /// </summary>
        internal static string MeasurementProbeFileName {
            get {
                return ResourceManager.GetString("MeasurementProbeFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to collect ultrasonic data from the DSI and probes at this time?.
        /// </summary>
        internal static string MessageCollect {
            get {
                return ResourceManager.GetString("MessageCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to copy from the old DSI or start from scratch?.
        /// </summary>
        internal static string MessageCopyScratch {
            get {
                return ResourceManager.GetString("MessageCopyScratch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while trying to open the COM port..
        /// </summary>
        internal static string MessageErrorLoggerOpen {
            get {
                return ResourceManager.GetString("MessageErrorLoggerOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while trying to read from Data Logger..
        /// </summary>
        internal static string MessageErrorLoggerRead {
            get {
                return ResourceManager.GetString("MessageErrorLoggerRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to measure the entire DSI network or would you like to finish commissioning without an initial measurement?.
        /// </summary>
        internal static string MessageMeasure {
            get {
                return ResourceManager.GetString("MessageMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug your device into the DSI that you would like to add to the network and click OK..
        /// </summary>
        internal static string MessagePlug {
            get {
                return ResourceManager.GetString("MessagePlug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug your new DSI into the network.  DO NOT disconnect any existing DSIs..
        /// </summary>
        internal static string MessagePlugAdd {
            get {
                return ResourceManager.GetString("MessagePlugAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please plug into the complete string of DSIs.  Plugging into an individual DSI is acceptable if ONLY ultrasonic parameters are edited..
        /// </summary>
        internal static string MessagePlugAddEditReplace {
            get {
                return ResourceManager.GetString("MessagePlugAddEditReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug your new DSI into the network.  Be sure to remove the target DSI before connecting the replacement, but leave other DSIs connected..
        /// </summary>
        internal static string MessagePlugReplace {
            get {
                return ResourceManager.GetString("MessagePlugReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug your device into the DSI that you would like to reset.  Click the Reset button to perform the reset..
        /// </summary>
        internal static string MessageReset {
            get {
                return ResourceManager.GetString("MessageReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Data Logger to connect....
        /// </summary>
        internal static string MessageWaitLogger {
            get {
                return ResourceManager.GetString("MessageWaitLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: The DSI address will be changed to {0} and all existing information will be erased or overwritten. Click OK to continue..
        /// </summary>
        internal static string MessageWarning {
            get {
                return ResourceManager.GetString("MessageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Reset Address to reset the DSI to the factory address and return home..
        /// </summary>
        internal static string MessageWarningReset {
            get {
                return ResourceManager.GetString("MessageWarningReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        internal static string MinimumTitle {
            get {
                return ResourceManager.GetString("MinimumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin password has not been set.  Please enter a new password..
        /// </summary>
        internal static string NewPasswordPrompt {
            get {
                return ResourceManager.GetString("NewPasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please re-enter your password..
        /// </summary>
        internal static string NewPasswordSecondPrompt {
            get {
                return ResourceManager.GetString("NewPasswordSecondPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sensor.dat.
        /// </summary>
        internal static string PasswordFilename {
            get {
                return ResourceManager.GetString("PasswordFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commissioning requires administrator access.  Please enter the administrator password:.
        /// </summary>
        internal static string PasswordPrompt {
            get {
                return ResourceManager.GetString("PasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing measurement....
        /// </summary>
        internal static string PerformMeasurementProgress {
            get {
                return ResourceManager.GetString("PerformMeasurementProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant.
        /// </summary>
        internal static string PlantTitle {
            get {
                return ResourceManager.GetString("PlantTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Probes.
        /// </summary>
        internal static string ProbeCountTitle {
            get {
                return ResourceManager.GetString("ProbeCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe #{0}.
        /// </summary>
        internal static string ProbeNumber {
            get {
                return ResourceManager.GetString("ProbeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe #.
        /// </summary>
        internal static string ProbeNumberTitle {
            get {
                return ResourceManager.GetString("ProbeNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Logger....
        /// </summary>
        internal static string ProgressReadLogger {
            get {
                return ResourceManager.GetString("ProgressReadLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap quit {
            get {
                object obj = ResourceManager.GetObject("quit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit application?.
        /// </summary>
        internal static string QuitCaption {
            get {
                return ResourceManager.GetString("QuitCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit the application?.
        /// </summary>
        internal static string QuitMessage {
            get {
                return ResourceManager.GetString("QuitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading DSI {0} / {1}.
        /// </summary>
        internal static string ReadProgressDsiString {
            get {
                return ResourceManager.GetString("ReadProgressDsiString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting....
        /// </summary>
        internal static string ReadProgressWaiting {
            get {
                return ResourceManager.GetString("ReadProgressWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Velocity.
        /// </summary>
        internal static string ReferenceVelocityTitle {
            get {
                return ResourceManager.GetString("ReferenceVelocityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting the DSI....
        /// </summary>
        internal static string ResetDsiProgress {
            get {
                return ResourceManager.GetString("ResetDsiProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No config.
        /// </summary>
        internal static string ResetNoConfig {
            get {
                return ResourceManager.GetString("ResetNoConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SensorNetworks.
        /// </summary>
        internal static string RootDataFolderName {
            get {
                return ResourceManager.GetString("RootDataFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNI.
        /// </summary>
        internal static string RootXmlFolderName {
            get {
                return ResourceManager.GetString("RootXmlFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SensorNetworks.
        /// </summary>
        internal static string RootXmlFolderName_Legacy {
            get {
                return ResourceManager.GetString("RootXmlFolderName_Legacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning network....
        /// </summary>
        internal static string ScanProgress {
            get {
                return ResourceManager.GetString("ScanProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap select_icon {
            get {
                object obj = ResourceManager.GetObject("select_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the file(s) for review..
        /// </summary>
        internal static string SelectFilesForReviewPrompt {
            get {
                return ResourceManager.GetString("SelectFilesForReviewPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the file(s) for upload..
        /// </summary>
        internal static string SelectFilesForUploadPrompt {
            get {
                return ResourceManager.GetString("SelectFilesForUploadPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sensor_active {
            get {
                object obj = ResourceManager.GetObject("sensor_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sensor_icon {
            get {
                object obj = ResourceManager.GetObject("sensor_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sensor_inactive {
            get {
                object obj = ResourceManager.GetObject("sensor_inactive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sensor_red {
            get {
                object obj = ResourceManager.GetObject("sensor_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sensor_red_inactive {
            get {
                object obj = ResourceManager.GetObject("sensor_red_inactive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sensor_yellow {
            get {
                object obj = ResourceManager.GetObject("sensor_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sensor_yellow_inactive {
            get {
                object obj = ResourceManager.GetObject("sensor_yellow_inactive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSI Serial #.
        /// </summary>
        internal static string SerialNumberTitle {
            get {
                return ResourceManager.GetString("SerialNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup {0}.
        /// </summary>
        internal static string SetupTabTitle {
            get {
                return ResourceManager.GetString("SetupTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream shutter {
            get {
                return ResourceManager.GetStream("shutter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sidebar {
            get {
                object obj = ResourceManager.GetObject("sidebar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sidebar_active {
            get {
                object obj = ResourceManager.GetObject("sidebar_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spinner {
            get {
                object obj = ResourceManager.GetObject("spinner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string StateTitleAbout {
            get {
                return ResourceManager.GetString("StateTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AScan.
        /// </summary>
        internal static string StateTitleAscan {
            get {
                return ResourceManager.GetString("StateTitleAscan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Upload.
        /// </summary>
        internal static string StateTitleCloudUpload {
            get {
                return ResourceManager.GetString("StateTitleCloudUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or Edit.
        /// </summary>
        internal static string StateTitleCommAddEdit {
            get {
                return ResourceManager.GetString("StateTitleCommAddEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AScan.
        /// </summary>
        internal static string StateTitleCommAscan {
            get {
                return ResourceManager.GetString("StateTitleCommAscan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Network.
        /// </summary>
        internal static string StateTitleCommBuildNetwork {
            get {
                return ResourceManager.GetString("StateTitleCommBuildNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string StateTitleCommCamera {
            get {
                return ResourceManager.GetString("StateTitleCommCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect Data.
        /// </summary>
        internal static string StateTitleCommCollectData {
            get {
                return ResourceManager.GetString("StateTitleCommCollectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect DSI.
        /// </summary>
        internal static string StateTitleCommConnect {
            get {
                return ResourceManager.GetString("StateTitleCommConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect DSI.
        /// </summary>
        internal static string StateTitleCommConnectAdd {
            get {
                return ResourceManager.GetString("StateTitleCommConnectAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect DSI.
        /// </summary>
        internal static string StateTitleCommConnectReplace {
            get {
                return ResourceManager.GetString("StateTitleCommConnectReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy DSI?.
        /// </summary>
        internal static string StateTitleCommCopyDsi {
            get {
                return ResourceManager.GetString("StateTitleCommCopyDsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSI Data.
        /// </summary>
        internal static string StateTitleCommDsiData {
            get {
                return ResourceManager.GetString("StateTitleCommDsiData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSI Params.
        /// </summary>
        internal static string StateTitleCommDsiParams {
            get {
                return ResourceManager.GetString("StateTitleCommDsiParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSI Warning.
        /// </summary>
        internal static string StateTitleCommDsiWarning {
            get {
                return ResourceManager.GetString("StateTitleCommDsiWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Globals.
        /// </summary>
        internal static string StateTitleCommEditGlobals {
            get {
                return ResourceManager.GetString("StateTitleCommEditGlobals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commissioning.
        /// </summary>
        internal static string StateTitleCommMain {
            get {
                return ResourceManager.GetString("StateTitleCommMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure Network?.
        /// </summary>
        internal static string StateTitleCommMeasure {
            get {
                return ResourceManager.GetString("StateTitleCommMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Network.
        /// </summary>
        internal static string StateTitleCommNew {
            get {
                return ResourceManager.GetString("StateTitleCommNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Company.
        /// </summary>
        internal static string StateTitleCommNewCompany {
            get {
                return ResourceManager.GetString("StateTitleCommNewCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug in.
        /// </summary>
        internal static string StateTitleCommPlugin {
            get {
                return ResourceManager.GetString("StateTitleCommPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe Params.
        /// </summary>
        internal static string StateTitleCommProbeParams {
            get {
                return ResourceManager.GetString("StateTitleCommProbeParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Progress.
        /// </summary>
        internal static string StateTitleCommReadProgress {
            get {
                return ResourceManager.GetString("StateTitleCommReadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset DSI.
        /// </summary>
        internal static string StateTitleCommReset {
            get {
                return ResourceManager.GetString("StateTitleCommReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness.
        /// </summary>
        internal static string StateTitleCommThickness {
            get {
                return ResourceManager.GetString("StateTitleCommThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string StateTitleEmail {
            get {
                return ResourceManager.GetString("StateTitleEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string StateTitleHome {
            get {
                return ResourceManager.GetString("StateTitleHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hook Up DSI.
        /// </summary>
        internal static string StateTitleHookup {
            get {
                return ResourceManager.GetString("StateTitleHookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Data Logger.
        /// </summary>
        internal static string StateTitleReadLogger {
            get {
                return ResourceManager.GetString("StateTitleReadLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Progress.
        /// </summary>
        internal static string StateTitleReadProgress {
            get {
                return ResourceManager.GetString("StateTitleReadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Existing Files.
        /// </summary>
        internal static string StateTitleReview {
            get {
                return ResourceManager.GetString("StateTitleReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Network.
        /// </summary>
        internal static string StateTitleScanNetwork {
            get {
                return ResourceManager.GetString("StateTitleScanNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string StateTitleSettings {
            get {
                return ResourceManager.GetString("StateTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string StateTitleSummary {
            get {
                return ResourceManager.GetString("StateTitleSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness.
        /// </summary>
        internal static string StateTitleThickness {
            get {
                return ResourceManager.GetString("StateTitleThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Files.
        /// </summary>
        internal static string StateTitleUpload {
            get {
                return ResourceManager.GetString("StateTitleUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string StatisticsTitle {
            get {
                return ResourceManager.GetString("StatisticsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to summary.csv.
        /// </summary>
        internal static string SummaryCsvFilename {
            get {
                return ResourceManager.GetString("SummaryCsvFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Alarm.
        /// </summary>
        internal static string SystemAlarmTitle {
            get {
                return ResourceManager.GetString("SystemAlarmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness Alarm State.
        /// </summary>
        internal static string ThicknessAlarmStateTitle {
            get {
                return ResourceManager.GetString("ThicknessAlarmStateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness Alarm Threshold.
        /// </summary>
        internal static string ThicknessAlarmThresholdTitle {
            get {
                return ResourceManager.GetString("ThicknessAlarmThresholdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness Alarm.
        /// </summary>
        internal static string ThicknessAlarmTitle {
            get {
                return ResourceManager.GetString("ThicknessAlarmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness Warning Threshold.
        /// </summary>
        internal static string ThicknessWarningThresholdTitle {
            get {
                return ResourceManager.GetString("ThicknessWarningThresholdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time/Date ({0}).
        /// </summary>
        internal static string TimeDateTitle {
            get {
                return ResourceManager.GetString("TimeDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap upload_fail {
            get {
                object obj = ResourceManager.GetObject("upload_fail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap upload_icon {
            get {
                object obj = ResourceManager.GetObject("upload_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap upload_success {
            get {
                object obj = ResourceManager.GetObject("upload_success", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string UploadComplete {
            get {
                return ResourceManager.GetString("UploadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading file {0} / {1}.
        /// </summary>
        internal static string UploadProgressString {
            get {
                return ResourceManager.GetString("UploadProgressString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap view_icon {
            get {
                object obj = ResourceManager.GetObject("view_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
