//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DsiApi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TabletApp.Api.DsiApi.ApiResources", typeof(ApiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out waiting for data logger heartbeat message. Giving up..
        /// </summary>
        internal static string ErrorFailedToReadLoggerHeartbeat {
            get {
                return ResourceManager.GetString("ErrorFailedToReadLoggerHeartbeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for DSI..
        /// </summary>
        internal static string ErrorFireShotClearDataReadyBitTimeout {
            get {
                return ResourceManager.GetString("ErrorFireShotClearDataReadyBitTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout waiting for data ready bit to read shot results..
        /// </summary>
        internal static string ErrorFireShotDataReadyBitTimeout {
            get {
                return ResourceManager.GetString("ErrorFireShotDataReadyBitTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read probe information from the DSI..
        /// </summary>
        internal static string ErrorFireShotReadProbeInfo {
            get {
                return ResourceManager.GetString("ErrorFireShotReadProbeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read setup information from the DSI..
        /// </summary>
        internal static string ErrorFireShotReadSetupInfo {
            get {
                return ResourceManager.GetString("ErrorFireShotReadSetupInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fire the shot. Could not set the fire register to fire the shot..
        /// </summary>
        internal static string ErrorFireShotSetFireRegister {
            get {
                return ResourceManager.GetString("ErrorFireShotSetFireRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fire the shot. Could not set the probe number to fire..
        /// </summary>
        internal static string ErrorFireShotSetProbeNumber {
            get {
                return ResourceManager.GetString("ErrorFireShotSetProbeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fire the shot. Could not set the setup number to fire..
        /// </summary>
        internal static string ErrorFireShotSetSetupNumber {
            get {
                return ResourceManager.GetString("ErrorFireShotSetSetupNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gates are null or empty..
        /// </summary>
        internal static string ErrorGateListEmpty {
            get {
                return ResourceManager.GetString("ErrorGateListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        internal static string ErrorLoginInvalidUserPass {
            get {
                return ResourceManager.GetString("ErrorLoginInvalidUserPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server response was not OK (200)..
        /// </summary>
        internal static string ErrorLoginUnexpectedServerResponse {
            get {
                return ResourceManager.GetString("ErrorLoginUnexpectedServerResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device returned exception code {0}
        ///Command: {1}.
        /// </summary>
        internal static string ErrorModBusException {
            get {
                return ResourceManager.GetString("ErrorModBusException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port name is undefined.
        ///
        ///Go to Settings and select a COM port..
        /// </summary>
        internal static string ErrorPortName {
            get {
                return ResourceManager.GetString("ErrorPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open port named &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorPortOpen {
            get {
                return ResourceManager.GetString("ErrorPortOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probes are null or empty..
        /// </summary>
        internal static string ErrorProbeListEmpty {
            get {
                return ResourceManager.GetString("ErrorProbeListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to disable data logging when reading logged shots..
        /// </summary>
        internal static string ErrorReadLoggedShotsDisableLogging {
            get {
                return ResourceManager.GetString("ErrorReadLoggedShotsDisableLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to enable data logging after reading logged shots..
        /// </summary>
        internal static string ErrorReadLoggedShotsEnableLogging {
            get {
                return ResourceManager.GetString("ErrorReadLoggedShotsEnableLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read logged shots. Failed to prepare to read shot {0} of probe {1} from data logger DSI..
        /// </summary>
        internal static string ErrorReadLoggedShotsPrepareNextShotSetBit {
            get {
                return ResourceManager.GetString("ErrorReadLoggedShotsPrepareNextShotSetBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read logged shot count..
        /// </summary>
        internal static string ErrorReadLoggedShotsReadShotCount {
            get {
                return ResourceManager.GetString("ErrorReadLoggedShotsReadShotCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read logged shots. Could not set the probe number to read..
        /// </summary>
        internal static string ErrorReadLoggedShotsSetProbeNumber {
            get {
                return ResourceManager.GetString("ErrorReadLoggedShotsSetProbeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set realtime clock when enabling data logger mode after reading logged shots..
        /// </summary>
        internal static string ErrorReadLoggedShotsSetRealTimeClock {
            get {
                return ResourceManager.GetString("ErrorReadLoggedShotsSetRealTimeClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read logged shots. Could not set the setup number, always 0, to read..
        /// </summary>
        internal static string ErrorReadLoggedShotsSetSetupNumber {
            get {
                return ResourceManager.GetString("ErrorReadLoggedShotsSetSetupNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setups are null or empty..
        /// </summary>
        internal static string ErrorSetupListEmpty {
            get {
                return ResourceManager.GetString("ErrorSetupListEmpty", resourceCulture);
            }
        }
    }
}
